[paths]
; install_files = Y:\SiemensNX-2506.7002_wntx64
install_files = X:\SiemensNX-2206_wntx64
install_dir   = C:\Apps\NX\
temp_dir      = C:\Temp\NXInstall\

[features]
selected = FEAT_CORE,FEAT_NXPLATFORM,FEAT_PROGRAMMING_TOOLS,FEAT_COMPOSITES,FEAT_MECHATRONICS,FEAT_SIMULATION,FEAT_TRANSLATORS,FEAT_STUDIO_RENDER

[prerequisites]
install_vcpp   = true
install_dotnet = true

[license]
splm_license_server = 28000@10.10.220.13

; [user]
; name = alexander
; surname = helbok

[downloads]
fcc_url = https://drive.google.com/file/d/1Try6q5Ny-vS5XYJEBXeErtTL35xpmXdE/view?usp=drive_link
; java_url = https://drive.google.com/file/d/1xrGcm7mU9uHlUI64y-AfguhQUTrj4iN8/view?usp=drive_link
java_url = https://drive.google.com/file/d/1U82NRAYErxCTvkayVKvlWqKHQG9XkpIP/view?usp=drive_link
start_nx_url = https://drive.google.com/file/d/1MLdo92UoRPNKrRCYqzPmR2dAPIzPiY3X/view?usp=drive_link
role_url = https://drive.google.com/file/d/12eQPvcrtmgydg7UlfEOWbpYV_3cD7RVb/view?usp=drive_link
dpv_url = https://drive.google.com/file/d/1NdePHgT5etRh5xLlD42Jl7hrDtk3_81e/view?usp=drive_link
fcg_url = https://drive.google.com/file/d/1TsoDtZ874T0rTBScjn9xJVLOD7J7EdD5/view?usp=drive_link

[logging]
log_level = INFO

[timeouts]
install_timeout_seconds = 5400
